api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/User/Entity'
      - '%kernel.project_dir%/src/Auth/Entity'
      - '%kernel.project_dir%/src/Post/Entity'
      - '%kernel.project_dir%/src/Main/Entity'
  patch_formats:
    json: ['application/merge-patch+json', 'application/json']
  swagger:
    versions: [3]
  eager_loading:
    enabled: false
  defaults:
    pagination_client_enabled: true
  collection:
    pagination:
      enabled_parameter_name: pagination
