api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
      - '%kernel.project_dir%/src/DTO'
  patch_formats:
    json: ['application/merge-patch+json', 'application/json']
    multipart: ['multipart/form-data']
  swagger:
    versions: [3]
  eager_loading:
    enabled: false
  defaults:
    pagination_client_enabled: true
  collection:
    pagination:
      enabled_parameter_name: pagination
