flysystem:
  storages:
    users.storage:
      adapter: 'aws'
      # visibility: public # Make the uploaded file publicly accessible in S3
      options:
        client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
        bucket: '%env(AWS_S3_BUCKET_NAME)%'
